export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const SET_TEXT = 'SET_TEXT'
export const SET_COUNTER = 'SET_COUNTER'

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING'
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS'
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED'
